'use strict';
const M=window.BesedkaEditorModel,G=window.BesedkaGeometry,S=window.BesedkaSolar,$=id=>document.getElementById(id),key='besedka-editor-v2';
const defaults={length:4,width:3,height:2.5,roof:'shed',rise:1,cover:'pergola',section:100,material:'Древесина, без окраски',notes:'Пристройка к дому. Пол пока не предусмотрен, основание планируется.'};
const input=(id,label,value,props='')=>`<label>${label}<input id="${id}" value="${value}" ${props}></label>`;
const numeric=(id,label,value,min=-100000,max=100000)=>input(id,label,value,`type="number" min="${min}" max="${max}" step="1" required`);
const select=(id,label,options)=>`<label>${label}<select id="${id}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>`;
const materials=[['wood','Древесина'],['metal','Металл'],['roof','Кровля'],['other','Другой материал']];
const sizes=(prefix,values)=>'<div class="sizes">'+['Ширина','Длина','Толщина'].map((s,i)=>numeric(prefix+'-'+['width','length','depth'][i],s+', мм',values[i],1,60000)).join('')+'</div>';
$('add-form').innerHTML=select('new-kind','Что добавляем',[['post','Стойка'],['beam','Балка / брус'],['board','Доска'],['brace','Укосина'],['rafter','Стропило'],['panel','Панель / покрытие'],['round','Круглая опора']])+input('new-name','Название','Новая стойка','maxlength="100"')+sizes('new',[100,2500,100])+select('new-orientation','Как расположить',[['vertical','Вертикально — стойка'],['width','Горизонтально — вдоль фасада'],['depth','Горизонтально — в глубину'],['slant','Наклонно — 45°']])+select('new-material','Материал',materials)+'<button type="submit">+ Добавить в модель</button><p class="hint">Деталь появится рядом с беседкой. Выберите «Двигать деталь» или задайте точное положение.</p>';
$('parameters').innerHTML=['length','width','height'].map((k,i)=>input(k,['Длина, м','Ширина, м','Нижний край, м'][i],defaults[k],`type="number" min="${i===2?1:.5}" max="${i===2?10:30}" step="0.01" required`)).join('')+select('roof','Крыша',[['shed','Односкатная'],['gable','Двускатная'],['flat','Плоская']])+input('rise','Подъём, м',1,'type="number" min="0.1" max="5" step="0.01"')+select('cover','Покрытие',[['pergola','Открытая пергола'],['solid','Сплошное']])+numeric('section','Сечение бруса, мм',100,50,300)+'<button type="submit">Заменить исходным примером</button>';
$('properties-form').innerHTML='<div id="single-fields">'+input('part-name','Название','','maxlength="100"')+sizes('part',[100,2500,100])+'</div>'+select('part-material','Материал',materials)+input('material-name','Название материала','','maxlength="100"')+input('part-color','Цвет','#b89569','type="color"')+'<button type="submit">Применить изменения</button>';
$('position-tools').innerHTML='<details open><summary>Точное положение</summary><p class="hint">Координаты центра детали или группы, мм. Высота отсчитывается от земли.</p><form id="position-form">'+['x','y','z'].map((k,i)=>numeric('position-'+k,['Влево / вправо','Высота центра','В глубину'][i],0)).join('')+'<button type="submit" class="secondary">Установить точно</button></form></details>'+numeric('move-step','Шаг перемещения, мм',50,1,5000)+'<div class="move-buttons">'+[[0,-1,'← Влево'],[0,1,'Вправо →'],[1,1,'↑ Выше'],[1,-1,'↓ Ниже'],[2,-1,'Назад'],[2,1,'Вперёд']].map(([a,s,t])=>`<button data-move="${a},${s}" class="secondary">${t}</button>`).join('')+'</div><details><summary>Поворот и стыковка</summary>'+select('turn-axis','Как повернуть',[['1','Как на поворотном столе'],['0','Наклон вперёд / назад'],['2','Наклон влево / вправо']])+numeric('turn-angle','На сколько градусов',90,-360,360)+'<button id="turn" class="secondary">Повернуть выбранное</button>'+select('align-target','Приставить к детали',[])+select('align-axis','Направление',[['0','По ширине'],['1','По высоте'],['2','В глубину']])+select('align-side','Куда приставить',[['end','После неё'],['start','Перед ней'],['centre','Совместить центры']])+numeric('align-gap','Зазор, мм',0,-5000,5000)+'<button id="align" class="secondary">Приставить точно</button><p class="hint">Стыковка по внешним габаритам. Скошенные соединения нужно проверить отдельно.</p></details><div class="actions-grid"><button id="duplicate" class="secondary">Сделать копию</button><button id="visibility" class="secondary">Скрыть</button><button id="lock" class="secondary">Защитить от правок</button><button id="delete" class="danger">Удалить выбранное</button></div>';
let initial,storageAvailable=true;
try{const saved=localStorage.getItem(key),old=localStorage.getItem('besedka-work-v1');initial=saved?M.load(saved):old?M.load(old):M.example(defaults);}catch{initial=M.example(defaults);storageAvailable=false;}
let history=M.history(initial),work=history.value,selected=[],memberId=null,editingMember=false,svg='',fileUrl=null;
const num=id=>Number($(id).value),message=text=>{$('feedback').textContent=text;};
const chosen=()=>M.selection(work,selected,false);
function saveLocal(){try{localStorage.setItem(key,JSON.stringify(work));storageAvailable=true;$('save-status').textContent='Сохранено на этом устройстве';}catch{storageAvailable=false;$('save-status').textContent='Автосохранение недоступно — сохраните файл';}}
function commit(next,status='Изменения применены.'){stopSun();work=history.commit(next);selected=selected.filter(id=>work.parts.some(p=>p.id===id));memberId=null;editingMember=false;saveLocal();refresh();message(status);}
function act(fn,status){try{commit(fn(),status);}catch(e){message(e.message);}}
function pick(id,append=false){const ids=M.selection(work,[id]);selected=append?(selected.includes(id)?selected.filter(i=>!ids.includes(i)):[...new Set([...selected,...ids])]):ids;memberId=id;editingMember=false;refresh();}
function download(data,type,name){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function xml(v){return String(v).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));}
function scene(canvas,interactive=true){
  const ctx=canvas.getContext('2d'),shadowLayer=document.createElement('canvas');let data={vertices:[],faces:[]},yaw=.65,pitch=.45,zoom=1,mode='design',tool='rotate',painted=[],scale=1,frame=null,drag=null,pointers=new Map(),pinch=null;
  function render(){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const ratio=Math.min(devicePixelRatio||1,2);canvas.width=r.width*ratio;canvas.height=r.height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);const bg=ctx.createLinearGradient(0,0,0,r.height);bg.addColorStop(0,mode==='design'?'#f5f0e6':'#f6fafb');bg.addColorStop(1,mode==='design'?'#dfe6d8':'#e3edf0');ctx.fillStyle=bg;ctx.fillRect(0,0,r.width,r.height);if(mode==='engineering'){ctx.strokeStyle='#d6e3e6';ctx.lineWidth=.5;for(let x=0;x<r.width;x+=25){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,r.height);ctx.stroke();}for(let y=0;y<r.height;y+=25){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(r.width,y);ctx.stroke();}}
    if(!data.vertices.length){ctx.fillStyle='#65766a';ctx.font='18px system-ui';ctx.textAlign='center';ctx.fillText('Добавьте первую деталь',r.width/2,r.height/2);ctx.textAlign='left';painted=[];return;}
    const lo=[0,1,2].map(i=>Math.min(...data.vertices.map(v=>v[i]))),hi=[0,1,2].map(i=>Math.max(...data.vertices.map(v=>v[i])));if(!frame)frame={centre:lo.map((n,i)=>(n+hi[i])/2),size:Math.max(...hi.map((n,i)=>n-lo[i]),1)};scale=Math.min(r.width*.72,r.height*.7)/frame.size*zoom;
    const project=v=>{const [x,y,z]=v.map((n,i)=>n-frame.centre[i]),a=x*Math.cos(yaw)+z*Math.sin(yaw),b=-x*Math.sin(yaw)+z*Math.cos(yaw);return [r.width/2+a*scale,r.height/2-(y*Math.cos(pitch)-b*Math.sin(pitch))*scale,y*Math.sin(pitch)+b*Math.cos(pitch)];};
    const polygon=(context,poly)=>{context.beginPath();poly.forEach((p,i)=>i?context.lineTo(p[0],p[1]):context.moveTo(p[0],p[1]));context.closePath();};
    if(interactive){
      const environment=work.environment,sun=S.position(environment);
      if(mode==='design'&&environment.background){
        const sky=ctx.createLinearGradient(0,0,0,r.height);sky.addColorStop(0,sun.daylight?'#d8e8e5':'#36445b');sky.addColorStop(1,sun.daylight?'#f2ead6':'#8d998d');ctx.fillStyle=sky;ctx.fillRect(0,0,r.width,r.height);
        for(let layer=0;layer<2;layer++){ctx.beginPath();ctx.moveTo(0,r.height);ctx.lineTo(0,r.height*.57);for(let x=0;x<=r.width;x+=8)ctx.lineTo(x,r.height*(.58+layer*.045)+Math.sin(x/r.width*7+layer)*r.height*.025+Math.sin(x/r.width*19)*r.height*.008);ctx.lineTo(r.width,r.height);ctx.closePath();ctx.fillStyle=layer?'#a8b8a0':'#c3cec0';ctx.fill();}
      }
      const radius=frame.size*1.4,c=frame.centre,ground=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,z])=>project([c[0]+x*radius,0,c[2]+z*radius]));
      if(environment.ground){polygon(ctx,ground);ctx.fillStyle=mode==='design'?(sun.daylight?'#c2aa86':'#8c806f'):'#e6e3d8';ctx.fill();ctx.save();ctx.clip();if(mode==='design'){ctx.fillStyle='#79664038';for(let x=-12;x<=12;x++)for(let z=-12;z<=12;z++){const p=project([c[0]+(x+.25*Math.sin(z*13+x))*radius/12,0,c[2]+(z+.25*Math.cos(x*17-z))*radius/12]);ctx.beginPath();ctx.ellipse(p[0],p[1],1.4,.65,0,0,Math.PI*2);ctx.fill();}}else{ctx.strokeStyle='#b6b6a96b';ctx.lineWidth=.6;for(let n=-12;n<=12;n++){const a=project([c[0]+n*radius/12,0,c[2]-radius]),b=project([c[0]+n*radius/12,0,c[2]+radius]);ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke();}}ctx.restore();}
      if(environment.shadows&&sun.daylight){
        // Draw an opaque union first, then blend once: overlapping faces do not darken twice.
        const layer=shadowLayer;layer.width=canvas.width;layer.height=canvas.height;const shadowCtx=layer.getContext('2d');shadowCtx.setTransform(ratio,0,0,ratio,0,0);shadowCtx.fillStyle='#27352a';
        for(const f of data.faces){const projected=f.v.map(i=>project(S.shadow(data.vertices[i],sun.direction)));polygon(shadowCtx,projected);shadowCtx.fill();}
        ctx.save();if(environment.ground){polygon(ctx,ground);ctx.clip();}ctx.globalAlpha=mode==='design'?.28:.19;ctx.drawImage(layer,0,0,r.width,r.height);ctx.restore();
      }
      ctx.fillStyle='#314b3e';ctx.font='12px system-ui';const centre=[r.width-38,40],n=environment.north*Math.PI/180,origin=project([c[0],0,c[2]]),tip=project([c[0]+Math.sin(n),0,c[2]-Math.cos(n)]),dx=tip[0]-origin[0],dy=tip[1]-origin[1],len=Math.hypot(dx,dy)||1;
      ctx.beginPath();ctx.arc(...centre,24,0,Math.PI*2);ctx.fillStyle='#fffef9da';ctx.fill();ctx.strokeStyle='#476451';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(centre[0]-dx/len*9,centre[1]-dy/len*9);ctx.lineTo(centre[0]+dx/len*13,centre[1]+dy/len*13);ctx.stroke();ctx.fillStyle='#314b3e';ctx.fillText('С',centre[0]+dx/len*16-4,centre[1]+dy/len*16+4);
      ctx.fillText(sun.daylight?'Солнце '+formatTime(environment.hour)+' · '+Math.round(sun.altitude)+'°':'Солнце за горизонтом',14,24);
      ctx.fillText('Тень примерная · '+(environment.northKnown?'север задан':'север условный'),14,43);
    }
    const pts=data.vertices.map(project);
    painted=data.faces.map(f=>({f,pts:f.v.map(i=>pts[i]),depth:f.v.reduce((s,i)=>s+pts[i][2],0)/f.v.length})).sort((a,b)=>a.depth-b.depth);
    ctx.lineJoin='round';for(let j=0;j<painted.length;j++){const {f,pts:poly}=painted[j];ctx.beginPath();poly.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();if(mode==='design'){ctx.fillStyle=f.color;ctx.fill();ctx.fillStyle=j%3===0?'#ffffff12':j%3===1?'#00000010':'#ffffff00';ctx.fill();}const isSelected=interactive&&!document.body.classList.contains('presentation')&&selected.includes(f.objectId);ctx.strokeStyle=isSelected?'#cf8838':mode==='design'?'#555f4938':'#526e83';ctx.lineWidth=isSelected?2.5:mode==='design'?.6:1;ctx.stroke();}
    if(mode==='engineering'){ctx.fillStyle='#355367';ctx.font='13px system-ui';const b=M.bounds(work);ctx.fillText(b.size.map(n=>(n*1000).toFixed(0)).join(' × ')+' мм · габариты',14,r.height-16);}
  }
  const hit=(x,y)=>{for(let k=painted.length-1;k>=0;k--){const poly=painted[k].pts;let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside;}if(inside)return painted[k].f.objectId;}return null;};
  const point=e=>{const r=canvas.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top];};
  if(interactive){canvas.addEventListener('pointerdown',e=>{const pos=point(e);pointers.set(e.pointerId,pos);canvas.setPointerCapture(e.pointerId);if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a[0]-b[0],a[1]-b[1]),zoom};if(drag&&drag.moved){work=drag.startWork;data=M.mesh(work);render();}drag=null;return;}const id=hit(...pos);if(tool==='move'&&id&&!selected.includes(id))pick(id);drag={id:tool==='move'?(id||selected[0]):id,start:pos,last:pos,startWork:work,moved:false,startScale:scale};});
    canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const pos=point(e);pointers.set(e.pointerId,pos);if(pinch&&pointers.size===2){const [a,b]=[...pointers.values()];zoom=Math.max(.3,Math.min(5,pinch.zoom*Math.hypot(a[0]-b[0],a[1]-b[1])/Math.max(pinch.distance,1)));render();return;}if(!drag)return;const dx=pos[0]-drag.start[0],dy=pos[1]-drag.start[1];if(Math.hypot(dx,dy)<5&&!drag.moved)return;drag.moved=true;if(tool==='move'&&drag.id&&selected.length){const step=Math.max(.001,Math.min(5,num('move-step')/1000||.05)),snap=n=>Math.round(n/step)*step;try{work=M.transform(drag.startWork,selected,{translation:[snap(dx/drag.startScale),0,snap(dy/drag.startScale)]});data=M.mesh(work);}catch(e){message(e.message);}}else if(tool==='rotate'){yaw+=(pos[0]-drag.last[0])*.008;pitch=Math.max(-.15,Math.min(Math.PI/2,pitch+(pos[1]-drag.last[1])*.008));}else message('Сначала выберите деталь в модели или списке.');drag.last=pos;render();});
    canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(drag){if(drag.moved&&tool==='move'&&drag.id)commit(work,'Деталь передвинута. Кнопка «Отменить» вернёт её обратно.');else if(!drag.moved&&drag.id)pick(drag.id);drag=null;}pinch=null;});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);if(drag&&drag.moved&&tool==='move'){work=drag.startWork;data=M.mesh(work);render();}drag=null;pinch=null;});
    canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.3,Math.min(5,zoom*Math.exp(-e.deltaY*.001)));render();},{passive:false});}
  if(!interactive){let last=null;canvas.addEventListener('pointerdown',e=>{last=point(e);canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!last)return;const next=point(e);yaw+=(next[0]-last[0])*.008;pitch=Math.max(-.15,Math.min(Math.PI/2,pitch+(next[1]-last[1])*.008));last=next;render();});for(const event of ['pointerup','pointercancel'])canvas.addEventListener(event,()=>{last=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.3,Math.min(5,zoom*Math.exp(-e.deltaY*.001)));render();},{passive:false});}
  new ResizeObserver(render).observe(canvas);
  return {set(next,fit=false){data=next;if(fit)frame=null;render();},render,angle(value){[yaw,pitch]=({perspective:[.65,.45],front:[0,0],side:[Math.PI/2,0],top:[0,Math.PI/2]})[value];zoom=1;render();},mode(value){mode=value;render();},zoomBy(n){zoom=Math.max(.3,Math.min(5,zoom*n));render();},tool(value){tool=value;if(value==='move'){yaw=0;pitch=Math.PI/2;}render();},fit(){frame=null;zoom=1;yaw=.65;pitch=.45;render();}};
}
const view=scene($('scene'));
function formatTime(hour){const m=Math.round(hour*60);return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');}
function sunStatus(){const v=work.environment,sun=S.position(v),day=S.daylight(v);$('sun-time').textContent=formatTime(v.hour);$('sun-mini-time').textContent=formatTime(v.hour);$('sun-mini-hour').value=v.hour;$('sun-status').textContent=(day.polar==='night'?'Полярная ночь.':day.polar==='day'?'Солнце над горизонтом весь день.':'Световой день ≈ '+formatTime(day.sunrise)+' — '+formatTime(day.sunset)+'.')+' '+(sun.daylight?'Высота солнца '+Math.round(sun.altitude)+'°, направление '+Math.round(sun.azimuth)+'° от севера.':'Солнце за горизонтом; прямой тени нет.')+(v.northKnown?' Направление отмечено как проверенное.':' Север пока условный — уточните для своего участка.');}
function refreshSun(){const v=work.environment;for(const field of ['date','latitude','longitude','timezone','north','hour'])$('sun-'+field).value=v[field];$('sun-north-known').checked=v.northKnown;for(const [id,key] of [['show-ground','ground'],['show-background','background'],['show-shadows','shadows']])$(id).checked=v[key];sunStatus();}
let sunAnimation=null;
function stopSun(save=false){if(sunAnimation!==null){cancelAnimationFrame(sunAnimation);sunAnimation=null;if(save)commit(work,'Показ движения тени завершён. Время можно менять вручную.');}$('sun-play').textContent='▶ Весь световой день';$('sun-play').setAttribute('aria-pressed','false');$('sun-mini-play').textContent='▶';$('sun-mini-play').setAttribute('aria-label','Показать день на модели');}
function setEnvironment(patch,status){stopSun();act(()=>({...work,environment:S.settings({...work.environment,...patch})}),status);}
$('sun-hour').oninput=()=>{stopSun();work={...work,environment:{...work.environment,hour:num('sun-hour')}};sunStatus();view.render();};
$('sun-hour').onchange=()=>commit(work,'Время изменено. Тень показана на земле.');
$('sun-date').onchange=()=>setEnvironment({date:$('sun-date').value},'Дата изменена.');
for(const [id,key] of [['show-ground','ground'],['show-background','background'],['show-shadows','shadows']])$(id).onchange=()=>setEnvironment({[key]:$(id).checked},'Окружение обновлено.');
$('sun-settings').onsubmit=e=>{e.preventDefault();setEnvironment({...Object.fromEntries(['latitude','longitude','timezone','north'].map(k=>[k,num('sun-'+k)])),northKnown:$('sun-north-known').checked},'Место и направление сохранены в этой работе.');};
$('whole-turn').onclick=()=>{stopSun();act(()=>M.transform(work,work.parts.map(p=>p.id),{rotation:[0,num('whole-angle'),0]}),'Вся беседка развёрнута. Размеры деталей и группы сохранены.');tool('rotate');view.fit();};
$('sun-play').onclick=()=>{if(sunAnimation!==null){stopSun(true);return;}const day=S.daylight(work.environment);if(day.polar==='night'){message('В эту дату солнце не поднимается над горизонтом. Выберите другой день.');return;}const start=performance.now(),from=day.sunrise+.02,to=day.sunset-.02;$('sun-play').textContent='Ⅱ Остановить показ';$('sun-play').setAttribute('aria-pressed','true');$('sun-mini-play').textContent='Ⅱ';$('sun-mini-play').setAttribute('aria-label','Остановить день на модели');const tick=now=>{const t=Math.min(1,(now-start)/20000);work={...work,environment:{...work.environment,hour:from+(to-from)*t}};$('sun-hour').value=work.environment.hour;sunStatus();view.render();if(t<1)sunAnimation=requestAnimationFrame(tick);else stopSun(true);};sunAnimation=requestAnimationFrame(tick);};
$('sun-mini-play').onclick=()=>$('sun-play').click();
$('sun-mini-hour').oninput=()=>{$('sun-hour').value=$('sun-mini-hour').value;$('sun-hour').oninput();};$('sun-mini-hour').onchange=()=>$('sun-hour').onchange();
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopSun(true);});
function drawings(){
  const b=M.bounds(work),mm=n=>Math.round(n*1000),sections=[[0,2,'Вид сверху',false],[0,1,'Фасад',true],[2,1,'Вид сбоку',true]];
  const hull=pts=>{const sorted=pts.map(p=>p.slice()).sort((a,b)=>a[0]-b[0]||a[1]-b[1]),cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]),lower=[],upper=[];for(const p of sorted){while(lower.length>1&&cross(lower.at(-2),lower.at(-1),p)<=0)lower.pop();lower.push(p);}for(const p of sorted.slice().reverse()){while(upper.length>1&&cross(upper.at(-2),upper.at(-1),p)<=0)upper.pop();upper.push(p);}return lower.slice(0,-1).concat(upper.slice(0,-1));};
  let body='';sections.forEach(([a,c,title,flip],section)=>{const top=75+section*270,scale=Math.min(600/Math.max(b.size[a],.1),175/Math.max(b.size[c],.1)),left=(800-b.size[a]*scale)/2;body+=`<text x="35" y="${top}">${title} · ${mm(b.size[a])} × ${mm(b.size[c])} мм</text>`;for(const p of work.parts){const pts=hull(M.points(p).map(v=>[left+(v[a]-b.min[a])*scale,top+28+(flip?b.max[c]-v[c]:v[c]-b.min[c])*scale]));body+=`<polygon points="${pts.map(v=>v.map(n=>n.toFixed(2)).join(',')).join(' ')}" fill="#edf1e8" stroke="#426452" stroke-width="1"/>`;}});
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 900"><style>text{font:16px Arial,sans-serif;fill:#263d32}</style><text x="35" y="36" style="font-size:25px">Беседка — габаритный эскиз</text>${body}<text x="35" y="885">Размеры по модели · все детали · без расчёта узлов и нагрузок</text></svg>`;
}
function refresh(){
  refreshSun();$('undo').disabled=!history.canUndo;$('quick-undo').disabled=!history.canUndo;$('jump-properties').disabled=!selected.length;$('redo').disabled=!history.canRedo;$('part-count').textContent=work.parts.length+' шт.';$('model-caption').textContent=work.parts.length?'Беседка · '+work.parts.length+' деталей · '+M.bounds(work).size.map(n=>(n*1000).toFixed(0)).join(' × ')+' мм':'Пустая модель — добавьте первую деталь';
  const list=$('parts-list');list.replaceChildren();const done=new Set();
  function row(p){const wrap=document.createElement('div');wrap.className='part-row'+(selected.includes(p.id)?' selected':'');const box=document.createElement('input');box.type='checkbox';box.checked=selected.includes(p.id);box.setAttribute('aria-label','Выбрать '+p.name);box.onchange=()=>pick(p.id,true);const button=document.createElement('button');button.textContent=p.name;button.type='button';const detail=document.createElement('small');detail.textContent=p.dimensions.map(n=>Math.round(n*1000)).join(' × ')+' мм · '+p.material.name+(p.hidden?' · скрыта':'')+(p.locked?' · защищена':'');button.append(detail);button.onclick=()=>pick(p.id);wrap.append(box,button);list.append(wrap);}
  for(const g of work.groups){const label=document.createElement('button');label.className='group-row secondary';label.textContent=g.name+' · '+g.members.length+' деталей';label.onclick=()=>pick(g.members[0]);list.append(label);for(const id of g.members){const p=work.parts.find(p=>p.id===id);row(p);done.add(id);}}
  work.parts.filter(p=>!done.has(p.id)).forEach(row);
  const ids=chosen(),first=work.parts.find(p=>p.id===(editingMember?memberId:ids[0])),single=ids.length===1||editingMember;
  $('selection-caption').textContent=first?(editingMember?'Размеры: '+first.name+'. Перемещение остаётся для всей группы.':ids.length===1?first.name:'Выбрано '+ids.length+' деталей. Материал меняется у всех выбранных.'): 'Нажмите на деталь в модели или её название в списке.';
  $('edit-member').hidden=!(ids.length>1&&memberId&&!editingMember);$('properties-form').hidden=!first;$('position-tools').hidden=!first;$('single-fields').hidden=!single;
  if(first){$('part-name').value=first.name;['width','length','depth'].forEach((k,i)=>$('part-'+k).value=Math.round(first.dimensions[i]*10000)/10);$('part-material').value=first.material.kind;$('material-name').value=first.material.name;$('part-color').value=first.material.color;const b=M.bounds(work,ids);['x','y','z'].forEach((k,i)=>$('position-'+k).value=Math.round(b.centre[i]*10000)/10);$('visibility').textContent=ids.every(id=>work.parts.find(p=>p.id===id).hidden)?'Показать':'Скрыть';$('lock').textContent=ids.some(id=>work.parts.find(p=>p.id===id).locked)?'Снять защиту':'Защитить от правок';}
  $('group').disabled=ids.length<2;$('ungroup').disabled=!work.groups.some(g=>g.members.some(id=>ids.includes(id)));
  $('align-target').replaceChildren();for(const p of work.parts.filter(p=>!ids.includes(p.id))){const option=document.createElement('option');option.value=p.id;option.textContent=p.name;$('align-target').append(option);}$('align').disabled=!$('align-target').options.length;
  svg=drawings();$('drawing').innerHTML=svg;$('bill').replaceChildren();for(const r of M.bill(work)){const tr=document.createElement('tr');for(const value of [r.names.length>1?r.names[0]+' и аналогичные':r.names[0],r.dimensions.join(' × '),String(r.count)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}const small=document.createElement('small');small.textContent=r.material;tr.firstChild.append(small);$('bill').append(tr);}
  $('notes').value=work.notes;for(const id of ['obj','png','svg','csv','print'])$(id).disabled=!work.parts.length;view.set(M.mesh(work));
}
const presets={post:{name:'Новая стойка',size:[100,2500,100],orientation:'vertical'},beam:{name:'Новая балка',size:[100,4000,100],orientation:'width'},board:{name:'Новая доска',size:[25,4000,100],orientation:'width'},brace:{name:'Новая укосина',size:[100,1000,100],orientation:'slant'},rafter:{name:'Новое стропило',size:[100,3200,100],orientation:'depth'},panel:{name:'Новое покрытие',size:[4000,3000,25],orientation:'depth'},round:{name:'Круглая опора',size:[100,2500,100],orientation:'vertical'}};
$('new-kind').onchange=()=>{const p=presets[$('new-kind').value];$('new-name').value=p.name;['width','length','depth'].forEach((k,i)=>$('new-'+k).value=p.size[i]);$('new-orientation').value=p.orientation;};
$('add-form').onsubmit=e=>{e.preventDefault();try{const rotation={vertical:[0,0,0],width:[0,0,-90],depth:[90,0,0],slant:[0,0,-45]}[$('new-orientation').value],bounds=M.bounds(work),next=M.add(work,{name:$('new-name').value,shape:$('new-kind').value==='round'?'cylinder':'box',dimensions:['width','length','depth'].map(k=>num('new-'+k)/1000),position:[bounds.max[0]+.4,1.25,0],rotation,material:{kind:$('new-material').value}});selected=[next.parts.at(-1).id];commit(next,'Деталь добавлена. Передвиньте её пальцем или задайте точное положение.');view.set(M.mesh(work),true);}catch(e){message(e.message);}};
$('parameters').onsubmit=e=>{e.preventDefault();act(()=>{selected=[];return M.example({...defaults,...Object.fromEntries(['length','width','height','roof','rise','cover','section'].map(k=>[k,$(k).value]))});},'Исходный пример построен. Все его детали можно менять отдельно.');tool('rotate');view.fit();};
$('empty-project').onclick=()=>{selected=[];act(()=>M.empty(),'Модель пуста. Добавьте первую деталь.');tool('rotate');view.fit();};
$('clear-selection').onclick=()=>{selected=[];memberId=null;editingMember=false;refresh();};
$('group').onclick=()=>act(()=>M.group(work,selected,$('group-name').value||'Группа'),'Детали объединены. Теперь они перемещаются вместе.');
$('ungroup').onclick=()=>act(()=>M.ungroup(work,selected),'Группа разделена. Положение деталей сохранено.');
$('edit-member').onclick=()=>{editingMember=true;refresh();};
$('properties-form').onsubmit=e=>{e.preventDefault();const patch={material:{kind:$('part-material').value,name:$('material-name').value,color:$('part-color').value}};if(selected.length===1||editingMember){patch.name=$('part-name').value;patch.dimensions=['width','length','depth'].map(k=>num('part-'+k)/1000);}act(()=>M.update(work,editingMember?[memberId]:selected,patch,!editingMember),'Размеры и материал обновлены.');};
$('part-material').onchange=()=>{const p=M.part({material:{kind:$('part-material').value}});$('part-color').value=p.material.color;$('material-name').value=p.material.name;};
$('position-form').onsubmit=e=>{e.preventDefault();act(()=>{const b=M.bounds(work,chosen());return M.transform(work,selected,{translation:['x','y','z'].map((k,i)=>num('position-'+k)/1000-b.centre[i])});},'Точное положение установлено.');};
for(const button of document.querySelectorAll('[data-move]'))button.onclick=()=>act(()=>{const [axis,sign]=button.dataset.move.split(',').map(Number),step=num('move-step');if(!Number.isFinite(step)||step<1||step>5000)throw Error('Шаг должен быть от 1 до 5000 мм.');const delta=[0,0,0];delta[axis]=step/1000*sign;return M.transform(work,selected,{translation:delta});},'Деталь передвинута на заданный шаг.');
$('turn').onclick=()=>act(()=>{const rotation=[0,0,0];rotation[num('turn-axis')]=num('turn-angle');return M.transform(work,selected,{rotation});},'Поворот применён.');
$('align').onclick=()=>act(()=>M.align(work,selected,$('align-target').value,num('align-axis'),$('align-side').value,num('align-gap')/1000),'Деталь приставлена по габаритам. Проверьте соединение в разных видах.');
$('duplicate').onclick=()=>{const before=new Set(work.parts.map(p=>p.id));act(()=>{const next=M.duplicate(work,selected);selected=next.parts.filter(p=>!before.has(p.id)).map(p=>p.id);return next;},'Копия создана рядом. Её можно передвинуть.');};
$('delete').onclick=()=>act(()=>M.remove(work,selected),'Выбранное удалено. Можно отменить.');
$('visibility').onclick=()=>act(()=>M.setFlags(work,selected,{hidden:!chosen().every(id=>work.parts.find(p=>p.id===id).hidden)}),'Видимость изменена. Скрытые детали остаются в файле и списке материалов.');
$('lock').onclick=()=>act(()=>M.setFlags(work,selected,{locked:!chosen().some(id=>work.parts.find(p=>p.id===id).locked)}),'Защита детали изменена.');
for(const id of ['undo','redo'])$(id).onclick=()=>{stopSun();work=history[id]();selected=[];memberId=null;editingMember=false;saveLocal();refresh();message(id==='undo'?'Последнее изменение отменено.':'Изменение возвращено.');};
function tool(value){view.tool(value);for(const k of ['rotate','move'])$(k+'-tool').setAttribute('aria-pressed',String(k===value));$('gesture-tip').textContent=value==='move'?'Вид сверху: передвигайте выбранную деталь пальцем. Высоту меняйте кнопками «Выше / Ниже». Шаг задаётся в миллиметрах.':'Касание выбирает деталь. Движение пальцем поворачивает вид. Два пальца — масштаб.';}
$('rotate-tool').onclick=()=>tool('rotate');$('move-tool').onclick=()=>tool('move');
for(const id of ['perspective','front','side','top'])$('angle-'+id).onclick=()=>{tool('rotate');view.angle(id);};
for(const mode of ['design','engineering'])$(mode+'-mode').onclick=()=>{view.mode(mode);for(const k of ['design','engineering'])$(k+'-mode').setAttribute('aria-pressed',String(k===mode));};
$('zoom-in').onclick=()=>view.zoomBy(1.25);$('zoom-out').onclick=()=>view.zoomBy(.8);$('reset').onclick=()=>{tool('rotate');view.fit();};
function tab(id){for(const k of ['model','plan']){const active=k===id;$(k+'-panel').hidden=!active;$('tab-'+k).setAttribute('aria-selected',String(active));$('tab-'+k).tabIndex=active?0:-1;}view.render();}
for(const k of ['model','plan']){$('tab-'+k).onclick=()=>tab(k);$('tab-'+k).onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'model':e.key==='End'?'plan':k==='model'?'plan':'model';tab(next);$('tab-'+next).focus();}};}
$('present').onclick=()=>{const active=document.body.classList.toggle('presentation');$('present').textContent=active?'Вернуться к работе':'Показать клиенту';tool('rotate');view.render();window.scrollTo({top:0,behavior:'auto'});};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('presentation'))$('present').click();});
$('save').onclick=()=>{download(JSON.stringify(work,null,2),'application/json','besedka-project.json');message('Файл работы содержит все детали, размеры, материалы и группы.');};
$('obj').onclick=()=>download(G.obj(M.mesh(work,{includeHidden:true})),'text/plain','besedka.obj');
$('svg').onclick=()=>download(svg,'image/svg+xml','besedka-drawing.svg');
function csvCell(v){let s=String(v);if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
$('csv').onclick=()=>{const rows=[['Деталь','Материал','Ширина мм','Длина мм','Толщина мм','Количество']];for(const r of M.bill(work))rows.push([r.names[0],r.material,...r.dimensions,r.count]);download('\ufeff'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n'),'text/csv;charset=utf-8','besedka-parts.csv');};
$('png').onclick=()=>{view.render();$('scene').toBlob(blob=>{if(blob)download(blob,'image/png','besedka-view.png');});};
$('print').onclick=()=>window.print();
$('restore').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error('Откройте файл работы размером до 2 МБ.');const next=M.load(await f.text());stopSun();work=history.commit(next);selected=[];memberId=null;editingMember=false;saveLocal();refresh();tool('rotate');view.fit();message('Работа открыта: детали, материалы и группы восстановлены.');}catch(err){message(err.message);}e.target.value='';};
$('notes').oninput=()=>{work={...work,notes:$('notes').value};saveLocal();};
$('save-notes').onclick=()=>act(()=>({...work,notes:$('notes').value}),'Заметки сохранены.');
$('reference').onchange=async e=>{const f=e.target.files[0];if(!f)return;const panel=$('reference-view');panel.replaceChildren();if(fileUrl){URL.revokeObjectURL(fileUrl);fileUrl=null;}try{if(f.size>20*1024*1024)throw Error('Откройте исходный файл размером до 20 МБ.');const ext=f.name.split('.').pop().toLowerCase();if(['obj','stl'].includes(ext)){const data=ext==='obj'?G.parseObj(await f.text()):G.parseStl(await f.arrayBuffer()),c=document.createElement('canvas');c.setAttribute('aria-label','Исходная модель');panel.append(c);scene(c,false).set(data,true);}else if(['pdf','png','jpg','jpeg','webp'].includes(ext)){fileUrl=URL.createObjectURL(new Blob([f],{type:({pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp'})[ext]}));const el=document.createElement(ext==='pdf'?'iframe':'img');el.src=fileUrl;el.title='Исходный файл';if(ext!=='pdf')el.alt='Исходное изображение';panel.append(el);}else throw Error('Поддерживаются OBJ, STL, PDF, PNG, JPG и WebP.');$('file-status').textContent=f.name+' · открыт только на вашем устройстве.';}catch(err){$('file-status').textContent=err.message;}e.target.value='';};
const steps=[['Начнём с готовой беседки','Можно сразу менять исходный пример. Коснитесь нужной детали в модели или нажмите её название в списке.','Стойка → Выбрать → Изменить'],['Добавляйте нужные детали','Откройте «Добавить деталь», выберите брус, доску или другую деталь и задайте размеры в миллиметрах. Нажмите «Добавить в модель».','100 × 2500 × 100 мм'],['Передвигайте и поправляйте','Кнопка «Двигать деталь» включает вид сверху. Передвигайте пальцем. Высоту меняйте кнопками «Выше / Ниже», а точное положение — числами. Если ошиблись, нажмите «Отменить».','Пальцем · Точные числа · Отменить'],['Сохраните и покажите','Нажмите «Сохранить работу»: получится файл со всеми деталями. Его можно открыть позже или прислать сюда. «Показать клиенту» скрывает инструменты. Чертежи и список деталей — на соседней вкладке.','Сохранить → Открыть → Показать']];
let guideIndex=0;function guideStep(){const [title,description,picture]=steps[guideIndex];$('guide-step').textContent='ШАГ '+(guideIndex+1)+' ИЗ '+steps.length;$('guide-title').textContent=title;$('guide-text').textContent=description;$('guide-picture').textContent=picture;$('guide-next').textContent=guideIndex===steps.length-1?'Начать работу':'Далее';}
function openGuide(){guideIndex=0;guideStep();$('guide').showModal();}
function closeGuide(){$('guide').close();try{sessionStorage.setItem('besedka-guide-v2','seen');}catch{}$('help').focus();}
$('help').onclick=openGuide;$('guide-close').onclick=closeGuide;$('guide-next').onclick=()=>{if(guideIndex===steps.length-1)closeGuide();else{guideIndex++;guideStep();}};
$('guide').addEventListener('cancel',()=>{try{sessionStorage.setItem('besedka-guide-v2','seen');}catch{}});
$('orientation-dismiss').onclick=()=>{$('orientation-tip').hidden=true;};
$('jump-add').onclick=()=>{const card=$('add-form').closest('details');card.open=true;card.scrollIntoView({block:'start',behavior:'auto'});};
$('jump-parts').onclick=()=>$('parts-list').closest('section').scrollIntoView({block:'start',behavior:'auto'});
$('jump-properties').onclick=()=>$('properties-form').closest('aside').scrollIntoView({block:'start',behavior:'auto'});
$('quick-undo').onclick=()=>$('undo').click();
refresh();tool('rotate');$('save-status').textContent=storageAvailable?'Работа на вашем устройстве':'Автосохранение недоступно — сохраните файл';message(storageAvailable?'Выберите деталь в модели или в списке.':'Сохранённую работу не удалось прочитать. Показан исходный пример; ваш старый файл не удалён.');
try{if(!sessionStorage.getItem('besedka-guide-v2'))openGuide();}catch{openGuide();}
