'use strict';
const assert=require('node:assert/strict');
const {validate,gazebo,obj,parseObj,parseStl}=require('./geometry.js');
const sample={length:6,width:4,height:2.5,roof:'gable',rise:1,material:'дерево'};
const model=gazebo(sample);
assert.equal(Math.max(...model.vertices.map(v=>v[1])),3.5);
assert.equal(Math.max(...model.vertices.map(v=>v[0]))-Math.min(...model.vertices.map(v=>v[0])),6);
assert.equal(Math.max(...model.vertices.map(v=>v[2]))-Math.min(...model.vertices.map(v=>v[2])),4);
const imported=parseObj(obj(model));
assert.deepEqual(imported.vertices,model.vertices);
assert.deepEqual(imported.faces.map(f=>f.v),model.faces.map(f=>f.v));
assert.deepEqual(imported.edges,model.edges);
assert.equal(Math.max(...gazebo({...sample,roof:'flat',rise:''}).vertices.map(v=>v[1])),2.5);
assert.equal(Math.max(...gazebo({...sample,roof:'shed'}).vertices.map(v=>v[1])),3.5);
for(const change of [{length:''},{width:Infinity},{height:false},{roof:'unknown'},{rise:0},{length:31}])assert.throws(()=>validate({...sample,...change}));
assert.throws(()=>parseObj('v 0 0 0\nf 1 2 3'));
assert.throws(()=>parseObj('v NaN 0 0\nf 1 1 1'));
assert.deepEqual(parseObj('v 0 0 0\nv 1 0 0\nv 0 1 0\nf -3 -2 -1').faces[0].v,[0,1,2]);
const binary=new ArrayBuffer(134),view=new DataView(binary);view.setUint32(80,1,true);view.setFloat32(108,1,true);view.setFloat32(124,1,true);
assert.equal(parseStl(binary).faces.length,1);
const ascii=new TextEncoder().encode('solid test\nfacet normal 0 0 1\nouter loop\nvertex 0 0 0\nvertex 1 0 0\nvertex 0 1 0\nendloop\nendfacet\nendsolid').buffer;
assert.equal(parseStl(ascii).vertices.length,3);
assert.throws(()=>parseStl(new TextEncoder().encode('vertex 0 0 0').buffer));
console.log('Проверено: размеры, крыши, экспорт/импорт OBJ, ASCII/binary STL и повреждённые файлы.');
