'use strict';
const {randomUUID}=require('node:crypto');
const PRODUCTS=[
 {id:'website',name:'Создание сайта',status:'available',billing:'once',price:40000,priceMax:400000,term:'Договор от 6 месяцев',delivery:'От 2 недель до 3 месяцев, в среднем 3 недели',description:'Анализ аудитории, болей, продукта и конкурентов. Стратегия и воронка, визуальная история, 3D, аватары, квизы, калькуляторы, видео, анимации и музыка по согласованному составу. Редакторы сайта и прайса. Возможна разработка логотипа и фирменного стиля.',support:'Обслуживание 6 месяцев. Новые внедрения оплачиваются отдельно.',problem:'Красивый сайт не объясняет ценность и теряет заявки.',benefit:'Понятный путь от запроса до обращения; материалы можно обновлять самостоятельно.',economics:'Меньше ручных правок и потерянных обращений. Эффект измеряем по заявкам и конверсии, без гарантии дохода.',dependencies:[],steps:['Согласовать аудиторию, задачу и критерии результата','Утвердить стратегию, структуру и дизайн','Собрать сайт, редакторы и согласованные интеграции','Проверить заявки, мобильную версию и передать сайт']},
 {id:'ai-automation',name:'AI-автоматизация',status:'available',billing:'once',price:20000,priceMax:null,term:'Разовый проект',delivery:'Индивидуально, в среднем 1 месяц',description:'Стратегия, автоответы, воронки и скрипты, лид-магниты, боты, автоматизация повторяющихся процессов и соединение площадок.',support:'3 месяца обновлений. Поддержка, API, хостинг и серверы рассчитываются отдельно.',problem:'Повторяющиеся операции отнимают время команды.',benefit:'Согласованный процесс выполняется автоматически, сложные случаи передаются человеку.',economics:'Сравниваем затраты на реализацию и поддержку с фактически сэкономленным временем.',dependencies:[],steps:['Описать процесс и стоимость ручной работы','Согласовать сценарий, ограничения и доступы','Настроить автоматизацию и обработку ошибок','Проверить реальные сценарии и передать инструкции']},
 {id:'analytics',name:'Сквозная аналитика',status:'available',billing:'monthly',price:15000,priceMax:null,term:'Договор от 6 месяцев',delivery:'1 месяц',description:'Сбор доступной статистики площадок в одном ЛК, путь заявки, скорость ответа и конверсия менеджеров, рекомендации. Связность данных зависит от доступов и возможностей площадок.',support:'Перечень источников и событий согласуется до подключения.',problem:'Непонятно, какая реклама и работа менеджеров приносят обращения.',benefit:'Единые показатели, видимые потери на этапах и основания для улучшений.',economics:'Помогает находить неэффективные расходы; финансовый эффект проверяем по фактическим данным.',dependencies:[],steps:['Согласовать источники, события и показатели','Получить доступы и подключить источники','Сверить тестовые события и путь заявки','Проверить отчёты и назначить регулярный разбор']},
 {id:'autoposting',name:'Автопостинг и маркетинговая стратегия',status:'available',billing:'monthly',price:10000,priceMax:null,term:'Договор от 6 месяцев',delivery:'1 месяц',description:'Анализ компании, ниши и медиасреды; контент-план, публикации и актуализация информации на согласованных площадках из ЛК. Продаётся вместе со сквозной аналитикой.',support:'Подключения и сроки обновления подтверждаются отдельно для каждой площадки. Модерация внешних площадок влияет на срок.',problem:'Контент выходит нерегулярно, сведения на площадках расходятся.',benefit:'Единый план публикаций и подтверждённые данные компании.',economics:'Меньше повторной ручной работы, результаты контента оцениваются вместе с аналитикой.',dependencies:['analytics'],steps:['Подключить сквозную аналитику и собрать сведения компании','Согласовать стратегию, площадки и контент-план','Подключить площадки и подготовить материалы','Проверить публикацию, актуальность и отчёт']},
 {id:'content-factory',name:'Контент завод',status:'development',billing:'monthly',price:null,priceMax:null,term:'Условия разрабатываются',delivery:'В разработке',description:'Планируется сбор постов, историй и роликов из фото, текста, голосовых и видео клиента, оценка запаса контента и рекомендации по съёмкам. Генерация контента и сериалов с AI-персонажами.',support:'Состав, сроки и стоимость не утверждены.',problem:'Не хватает времени и навыков на регулярное производство контента.',benefit:'Планируемый результат: понятный запас материалов и единый процесс производства.',economics:'Экономику определим по затратам на материал и его фактическому результату.',dependencies:[],steps:['Собрать требования','Согласовать прототип','Проверить пилот','Утвердить готовность и условия']},
 {id:'crm',name:'CRM-система',status:'development',billing:'monthly',price:null,priceMax:null,term:'Условия разрабатываются',delivery:'В разработке',description:'Продажи, аналитика, финансы, напоминания и задачи, контроль этапов и сервиса. Коммерческий модуль предлагается со сквозной аналитикой.',support:'Внутренняя CRM уже развивается; готовность клиентского внедрения проверяется отдельно.',problem:'Контакты, договорённости и задачи теряются между сотрудниками.',benefit:'Планируемый результат: история клиента и понятный следующий шаг по каждой сделке.',economics:'Оцениваем сокращение пропущенных обращений и ручных операций.',dependencies:['analytics'],steps:['Описать процесс продаж','Настроить воронки и роли','Перенести согласованные данные','Проверить сценарии команды']},
 {id:'chat',name:'Чат компании',status:'development',billing:'monthly',price:null,priceMax:null,term:'Условия разрабатываются',delivery:'В разработке',description:'Планируется собственный чат без внешнего мессенджера: обращения, запись, перенос, напоминания и сопровождение клиента.',support:'Состав, сроки и стоимость не утверждены.',problem:'Клиент не может удобно связаться или перенести запись.',benefit:'Планируемый результат: единый канал обращений и согласованные сценарии сопровождения.',economics:'Проверим экономию времени администратора и долю обработанных обращений.',dependencies:[],steps:['Определить сценарии','Подключить данные и доступы','Настроить ответы и передачу сотруднику','Проверить запись и напоминания']},
 {id:'ai-mpp',name:'АИ МПП',status:'development',billing:'monthly',price:null,priceMax:null,term:'Не определён',delivery:'В разработке',description:'Название зафиксировано владельцем. Состав требует описания.',support:'Цена и условия не определены.',problem:'Требует уточнения',benefit:'Требует уточнения',economics:'Требует уточнения',dependencies:[],steps:['Описать модуль','Согласовать состав','Подготовить пилот','Проверить результат']}
];
const {createFinanceAi}=require('./finance-ai');
function createCommercial({db,fail}){
 // Расходы на ИИ — дополнительный блок той же операции Финансов, а не отдельный журнал.
 const financeAi=createFinanceAi({fail});
 db.exec(`CREATE TABLE IF NOT EXISTS commercial_catalog(id INTEGER PRIMARY KEY CHECK(id=1),version INTEGER NOT NULL,data TEXT NOT NULL);CREATE TABLE IF NOT EXISTS finance_entries(id INTEGER PRIMARY KEY AUTOINCREMENT,owner_scope TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,data TEXT NOT NULL,request_id TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(owner_scope,request_id));CREATE TABLE IF NOT EXISTS finance_audit(id INTEGER PRIMARY KEY,entry_id INTEGER NOT NULL,at TEXT NOT NULL,actor TEXT NOT NULL,before_data TEXT,after_data TEXT NOT NULL);`);
 db.prepare('INSERT OR IGNORE INTO commercial_catalog VALUES(1,1,?)').run(JSON.stringify({products:PRODUCTS,packages:[{id:'partners',name:'Партнёры',status:'available',lines:PRODUCTS.filter(p=>p.status==='available').map(p=>({productId:p.id,quantity:1,unitPrice:p.price})),priceOnce:0,priceMonthly:50000,terms:'Для первых клиентов, вместе с которыми строится продукт. Все реализованные модули; специальные предложения на будущие разработки. 50 000 ₽/мес. Срок отдельно согласуется.',allAvailable:true},{id:'marketing-department',name:'Отдел Маркетинга',status:'draft',lines:[],priceOnce:null,priceMonthly:null,terms:'Выберите состав и установите стоимость пакета.',allAvailable:false}]}));
 const bad=m=>fail(400,m,{code:'VALIDATION_ERROR'});
 const txt=(v,max=5000)=>{if(typeof v!=='string'||v.length>max)bad('Проверьте текстовые поля');return v.trim()};
 const amount=(v,nullable=false)=>{if(nullable&&v===null)return null;if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>1e9||Math.abs(v*100-Math.round(v*100))>0.00001)bad('Сумма должна быть неотрицательной, не больше миллиарда, до двух знаков после запятой');return Math.round(v*100)/100};
 const id=v=>{if(typeof v!=='string'||!/^[a-z0-9][a-z0-9_-]{0,79}$/.test(v))bad('Неверный код');return v};
 const arr=(v,max)=>{if(!Array.isArray(v)||v.length>max)bad('Слишком много строк');return v};
 const day=v=>{const s=txt(v,10),d=new Date(s+'T00:00:00Z');if(!/^\d{4}-\d\d-\d\d$/.test(s)||!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==s)bad('Некорректная дата');return s};
 const get=()=>{const r=db.prepare('SELECT * FROM commercial_catalog WHERE id=1').get();return {version:r.version,...JSON.parse(r.data)}};
 const packageTotals=(pack,products)=>{
  let once=0,monthly=0,unknown=false;const ids=new Set(pack.lines.map(l=>l.productId)),missing=[];
  for(const l of pack.lines){const p=products.find(p=>p.id===l.productId);if(!p)continue;if(l.unitPrice===null){unknown=true;continue;}const cents=Math.round(l.unitPrice*100)*l.quantity;if(p.billing==='monthly')monthly+=cents;else once+=cents;for(const dep of p.dependencies)if(!ids.has(dep))missing.push(dep);}
  return {once:once/100,monthly:monthly/100,unknown,missing:[...new Set(missing)]};
 };
 const catalog=()=>{const value=get();return {...value,packages:value.packages.map(p=>({...p,totals:packageTotals(p,value.products)}))}};
 const save=(body)=>{
  const old=get();if(body.version!==old.version)fail(409,'Каталог изменён. Обновите страницу перед сохранением.');
  const products=arr(body.products,100).map(p=>{const value={id:id(p.id),status:p.status,billing:p.billing,price:amount(p.price,true),priceMax:amount(p.priceMax,true),dependencies:arr(p.dependencies,20).map(id),steps:arr(p.steps,20).map(s=>txt(s,500))};if(!['available','development'].includes(value.status)||!['once','monthly'].includes(value.billing))bad('Неизвестный статус модуля');for(const k of ['name','term','delivery','description','support','problem','benefit','economics'])value[k]=txt(p[k],k==='name'?160:5000);if(!value.name)bad('Укажите название модуля');if(value.priceMax!==null&&(value.price===null||value.priceMax<value.price))bad('Максимальная цена меньше минимальной');return value});
  const ids=new Set(products.map(p=>p.id));if(ids.size!==products.length||products.some(p=>p.dependencies.some(d=>!ids.has(d)||d===p.id)))bad('Проверьте зависимости модулей');
  const visiting=new Set(),visited=new Set();const visit=key=>{if(visiting.has(key))bad('Циклическая зависимость модулей');if(visited.has(key))return;visiting.add(key);products.find(p=>p.id===key).dependencies.forEach(visit);visiting.delete(key);visited.add(key)};products.forEach(p=>visit(p.id));
  const packages=arr(body.packages,100).map(p=>{const lines=arr(p.lines,100).map(l=>{if(!ids.has(l.productId))bad('Модуль пакета не найден');if(!Number.isInteger(l.quantity)||l.quantity<1||l.quantity>1000)bad('Количество от 1 до 1000');return {productId:l.productId,quantity:l.quantity,unitPrice:amount(l.unitPrice,true)}});if(new Set(lines.map(l=>l.productId)).size!==lines.length)bad('Модуль повторяется в пакете');const pack={id:id(p.id),name:txt(p.name,160),status:p.status,terms:txt(p.terms),allAvailable:!!p.allAvailable,lines,priceOnce:amount(p.priceOnce,true),priceMonthly:amount(p.priceMonthly,true)};if(!pack.name||!['draft','available'].includes(pack.status))bad('Проверьте название и статус пакета');const totals=packageTotals(pack,products);if(pack.status==='available'&&(totals.missing.length||!lines.length||totals.unknown||lines.some(l=>products.find(v=>v.id===l.productId).status!=='available')||pack.priceOnce===null||pack.priceMonthly===null))bad('Готовый пакет требует доступных модулей, их зависимостей и заполненных цен');return pack});
  if(new Set(packages.map(p=>p.id)).size!==packages.length)bad('Повторный код пакета');
  const changed=db.prepare('UPDATE commercial_catalog SET version=version+1,data=? WHERE id=1 AND version=?').run(JSON.stringify({products,packages}),body.version);if(!changed.changes)fail(409,'Каталог уже изменён');return catalog();
 };
 const scope=s=>{if(typeof s!=='string'||!db.prepare('SELECT 1 FROM companies WHERE code=? COLLATE NOCASE AND is_deleted=0').get(s))bad('Выберите проект');return s.toLowerCase()};
 const entry=(entryId,s)=>{const r=db.prepare('SELECT * FROM finance_entries WHERE id=? AND owner_scope=?').get(entryId,scope(s));if(!r)fail(404,'Операция не найдена');return r};
 const dto=r=>({id:r.id,version:r.version,createdAt:r.created_at,updatedAt:r.updated_at,...JSON.parse(r.data)});
 const validate=(body,s)=>{const data={type:body.type,state:body.state,date:day(body.date),amount:amount(body.amount),category:txt(body.category,100),counterparty:txt(body.counterparty||'',300),note:txt(body.note||'',4000),dealId:body.dealId===null||body.dealId===''||body.dealId===undefined?null:Number(body.dealId)};if(!['income','expense'].includes(data.type)||!['planned','actual','void'].includes(data.state)||!data.category)bad('Укажите тип, статус, категорию и положительную сумму');
  const ai=financeAi.normalize(body.ai,data);
  /* Неподтверждённая стоимость ИИ (costKnown=false без основания) записывается нулём:
     иначе «неизвестно» маскировалось бы положительной суммой-заглушкой. Обычные операции
     и оценки по-прежнему требуют положительной суммы. */
  const unconfirmed=Boolean(ai&&!ai.costKnown&&ai.costBasis===null);
  if(unconfirmed){if(data.amount!==0)bad('Неподтверждённая стоимость ИИ записывается нулевой суммой: укажите основание estimate, чтобы записать оценку')}
  else if(data.amount<=0)bad('Укажите тип, статус, категорию и положительную сумму');
  if(data.dealId!==null&&!db.prepare('SELECT 1 FROM deal_orders WHERE id=? AND owner_scope=?').get(data.dealId,s))bad('Сделка недоступна');
  if(ai){if(data.type!=='expense')bad('Расход на ИИ записывается расходом');data.ai=ai}
  return data};
 const saveEntry=(entryId,s,body,actor)=>{s=scope(s);const old=entryId?entry(entryId,s):null;if(old&&old.version!==body.version)fail(409,'Операция изменена. Обновите данные.');const requestId=entryId?old.request_id:id(body.requestId||randomUUID());if(!old){const previous=db.prepare('SELECT * FROM finance_entries WHERE owner_scope=? AND request_id=?').get(s,requestId);if(previous)return dto(previous)}const data=validate(body,s),now=new Date().toISOString();db.exec('BEGIN IMMEDIATE');try{let key=entryId;if(old){const changed=db.prepare('UPDATE finance_entries SET version=version+1,data=?,updated_at=? WHERE id=? AND version=?').run(JSON.stringify(data),now,key,body.version);if(!changed.changes)fail(409,'Операция уже изменена')}else key=Number(db.prepare('INSERT INTO finance_entries(owner_scope,data,request_id,created_at,updated_at) VALUES(?,?,?,?,?)').run(s,JSON.stringify(data),requestId,now,now).lastInsertRowid);db.prepare('INSERT INTO finance_audit(entry_id,at,actor,before_data,after_data) VALUES(?,?,?,?,?)').run(key,now,actor?.userName||'owner',old?.data||null,JSON.stringify(data));db.exec('COMMIT');return dto(entry(key,s))}catch(e){db.exec('ROLLBACK');throw e}};
 const finance=(s,from,to,offset=0)=>{s=scope(s);from=day(from);to=day(to);if(from>to)bad('Начало периода позже окончания');const values=db.prepare("SELECT * FROM finance_entries WHERE owner_scope=? AND json_extract(data,'$.date')>=? AND json_extract(data,'$.date')<=? ORDER BY json_extract(data,'$.date') DESC,id DESC").all(s,from,to);const totals={income:0,expense:0,plannedIncome:0,plannedExpense:0};for(const r of values){const d=JSON.parse(r.data);if(d.state==='void')continue;const key=d.state==='planned'?(d.type==='income'?'plannedIncome':'plannedExpense'):d.type;totals[key]+=Math.round(d.amount*100)}for(const k in totals)totals[k]/=100;
  // Сводка по ИИ считается по тем же операциям периода, отдельного журнала нет.
  const ai=financeAi.summary(values.map(r=>JSON.parse(r.data)));
  return {entries:values.slice(offset,offset+100).map(dto),total:values.length,totals:{...totals,balance:Math.round((totals.income-totals.expense)*100)/100},ai,from,to}};
 return {catalog,save,finance,saveEntry,aiRequestId:financeAi.requestId,aiSummary:financeAi.summary};
}
module.exports={createCommercial,PRODUCTS};
