'use strict';
const test=require('node:test'), assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const {mkdtempSync,rmSync}=require('node:fs');
const {tmpdir}=require('node:os');
const path=require('node:path');
const {createServerResourceQueue}=require('./server-resource-queue');
const actor={role:'owner',userId:7};
function fixture(t){const dir=mkdtempSync(path.join(tmpdir(),'server-resource-'));const db=new DatabaseSync(path.join(dir,'data.sqlite'));let time=Date.parse('2026-10-08T11:00:00Z');const api=createServerResourceQueue(db,{now:()=>time});const connections=[db];t.after(()=>{for(const c of connections)c.close();rmSync(dir,{recursive:true,force:true});});return{db,api,connections,file:path.join(dir,'data.sqlite'),now:()=>time,advance:n=>time+=n};}
const add=(api,key='one',extra={})=>api.add({requestKey:key,taskRef:'test-'+key,threadId:'thread-'+key,executor:'Codex',scope:'CRM only',notBefore:'2026-10-08T11:00:00Z',durationMinutes:5,...extra},actor).request;
const act=(api,action,extra={})=>api.act({action,revision:api.get(actor).revision,...extra},actor);
const idle=api=>act(api,'confirm_idle',{evidence:'Проверено: исполнителей нет, предыдущая операция не запускалась'});
test('initial unknown, FIFO, duplicate request and mutation conflicts',t=>{const{api}=fixture(t);const a=add(api),b=add(api,'two');assert.equal(api.get(actor).state,'unknown');assert.throws(()=>act(api,'claim',{requestId:a.id}),e=>e.status===409);idle(api);assert.throws(()=>act(api,'claim',{requestId:b.id}),e=>e.status===409);assert.equal(add(api).id,a.id);assert.throws(()=>add(api,'one',{scope:'changed'}),e=>e.status===409);const rev=api.get(actor).revision;add(api,'three');assert.throws(()=>api.act({action:'claim',revision:rev,requestId:a.id},actor),e=>e.status===409);});
test('two connections share one lease; token never appears in reads; survives restart',t=>{const{api,file,now,connections}=fixture(t);const a=add(api),b=add(api,'two');idle(api);const db2=new DatabaseSync(file);connections.push(db2);const other=createServerResourceQueue(db2,{now});const stale=other.get(actor).revision;const claimed=act(api,'claim',{requestId:a.id});assert.equal(claimed.resource.holder.id,a.id);assert.ok(claimed.leaseToken);assert.ok(!JSON.stringify(other.get(actor)).includes(claimed.leaseToken));assert.throws(()=>other.act({action:'claim',revision:stale,requestId:b.id},actor),e=>e.status===409);assert.equal(other.get(actor).holder.id,a.id);});
test('expired lease blocks handover and requires a known outcome; stale actor cannot finish new generation',t=>{const{api,advance}=fixture(t);const a=add(api),b=add(api,'two');idle(api);const first=act(api,'claim',{requestId:a.id});advance(300001);assert.equal(api.get(actor).state,'unknown');assert.equal(api.get(actor).holder.state,'uncertain');assert.throws(()=>act(api,'claim',{requestId:b.id}),e=>e.status===409);assert.throws(()=>act(api,'renew',{requestId:a.id,leaseToken:first.leaseToken,fence:1}),e=>e.status===409);assert.throws(()=>act(api,'confirm_idle',{evidence:'Нет связи'}),e=>e.status===400);act(api,'confirm_idle',{requestId:a.id,outcome:'no_write',evidence:'Проверены процессы и журнал: запись не начиналась'});const second=act(api,'claim',{requestId:b.id});assert.equal(second.resource.fence,2);assert.throws(()=>act(api,'release',{requestId:a.id,leaseToken:first.leaseToken,fence:1,evidence:'Поздно'}),e=>e.status===409);assert.equal(api.get(actor).holder.id,b.id);});
test('renew and release record owner/time/result and immutable history',t=>{const{api,db,advance}=fixture(t);const a=add(api);idle(api);const run=act(api,'claim',{requestId:a.id});advance(1000);const fields={requestId:a.id,leaseToken:run.leaseToken,fence:run.resource.fence};act(api,'renew',fields);assert.throws(()=>act(api,'release',{...fields,leaseToken:'wrong',evidence:'bad'}),e=>e.status===409);const done=act(api,'release',{...fields,evidence:'Проверка после работы прошла, консоль освобождена'});assert.equal(done.resource.state,'idle');assert.equal(done.resource.holder,null);const log=done.resource.history.find(x=>x.event==='released');assert.equal(log.executor,'Codex');assert.equal(log.threadId,'thread-one');assert.equal(log.scope,'CRM only');assert.ok(done.resource.history.some(x=>x.event==='renewed'&&x.actorId===7));assert.equal(Date.parse(done.resource.nextCheckAt)-Date.parse(done.resource.serverTime),900000);assert.throws(()=>db.exec("UPDATE server_resource_history SET note='fake'"),/Immutable/);});
test('unauthorized users, unknown fields, invalid dates and durations rejected; notBefore honored',t=>{const{api,advance}=fixture(t);for(const a of[null,{role:'editor',userId:7},{role:'owner'}]){assert.throws(()=>api.get(a),e=>e.status===403);assert.throws(()=>api.add({},a),e=>e.status===403);assert.throws(()=>api.act({},a),e=>e.status===403);}for(const extra of[{durationMinutes:0},{durationMinutes:61},{notBefore:'invalid'},{scope:''},{secret:'no'}])assert.throws(()=>add(api,'bad',extra),e=>e.status===400);const a=add(api,'later',{notBefore:'2026-10-08T11:01:00Z'});idle(api);assert.throws(()=>act(api,'claim',{requestId:a.id}),e=>e.status===409);advance(60000);act(api,'claim',{requestId:a.id});});
test('stale idle evidence does not authorize a later claim',t=>{const{api,advance}=fixture(t);const a=add(api);idle(api);advance(300000);assert.equal(api.get(actor).state,'unknown');assert.throws(()=>act(api,'claim',{requestId:a.id}),e=>e.status===409);idle(api);act(api,'claim',{requestId:a.id});});
