const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const {PRODUCTS}=require('../../../ops/crm/commercial');
const tick=()=>new Promise(r=>setImmediate(r));
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setup(){const dom=new JSDOM('<section></section>',{url:'https://example.test/#catalog',runScripts:'outside-only'}),w=dom.window,views={},calls=[];w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.SbCabinet={registerView:(key,v)=>views[key]=v};const catalog={version:1,products:PRODUCTS,packages:[]};let company='synapse-business';const ctx={identity:{role:'owner'},scopeParams:()=>({companyCode:company}),escapeHTML:escape,csrfOptions:(method,body)=>({method,body}),crmQuery:async(path,scope,options={})=>{calls.push({path,scope,options});if(path==='/catalog')return catalog;if(path==='/deals')return {deals:[]};return {entries:[],total:0,from:'2026-09-01',to:'2026-09-16',totals:{income:0,expense:0,plannedIncome:0,plannedExpense:0,balance:0}}}};w.eval(fs.readFileSync(__dirname+'/commercial.js','utf8'));return {dom,w,views,calls,ctx,root:w.document.querySelector('section'),switchProject:()=>company='other'}}
test('package builder computes separate prices and submits module selection, discount and terms',async()=>{const t=setup();t.views.catalog.render(t.root,t.ctx);await tick();t.root.querySelector('[data-new-package]').click();const f=t.w.document.querySelector('dialog form');f.elements.name.value='Отдел Маркетинга';for(const id of ['website','analytics','autoposting'])f.querySelector(`[data-line="${id}"] [data-pick]`).checked=true;f.elements.priceOnce.value='35000';f.elements.priceMonthly.value='22000';f.elements.terms.value='6 месяцев';f.dispatchEvent(new t.w.Event('input',{bubbles:true}));const summary=f.querySelector('[data-calculation]');assert.equal(summary.querySelectorAll('s').length,2);assert.match(summary.textContent,/40\s000/);assert.match(summary.textContent,/25\s000/);f.dispatchEvent(new t.w.Event('submit',{cancelable:true}));await tick();const save=t.calls.find(c=>c.options.method==='PUT');assert.equal(save.options.body.packages[0].priceOnce,35000);assert.equal(save.options.body.packages[0].priceMonthly,22000);assert.equal(save.options.body.packages[0].lines.length,3);assert.equal(save.options.body.products.length,8);t.dom.window.close()});
test('finance never writes on opening and refuses a stale project form',async()=>{const t=setup();t.views.finance.render(t.root,t.ctx);await tick();assert.ok(t.calls.every(c=>!c.options.method));t.root.querySelector('[data-new-entry=income]').click();await tick();const f=t.w.document.querySelector('dialog form');f.elements.amount.value='50000';f.elements.category.value='Партнёры';t.switchProject();t.views.finance.render(t.root,t.ctx);await tick();f.dispatchEvent(new t.w.Event('submit',{cancelable:true}));await tick();assert.ok(t.calls.every(c=>!c.options.method));assert.match(f.querySelector('[role=alert]').textContent,/Проект изменён/);t.dom.window.close()});
test('catalog and finances do not load for nonowner',()=>{const t=setup();t.ctx.identity.role='editor';t.views.catalog.render(t.root,t.ctx);t.views.finance.render(t.root,t.ctx);assert.equal(t.calls.length,0);t.dom.window.close()});

test('another company does not load or offer the Synapse catalog',async()=>{const t=setup();t.switchProject();t.views.catalog.render(t.root,t.ctx);await tick();assert.equal(t.calls.length,0);assert.match(t.root.textContent,/Каталог услуг Synapse принадлежит компании Synapse Бизнес/);t.dom.window.close()});
