'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require('jsdom');
const settle=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
function fixture(){
 const dom=new JSDOM('<div id="tasks-content"></div><span id="tasks-badge"></span><dialog id="task-create-dialog"><button data-task-create-close></button><form id="task-create-form"></form></dialog>',{url:'https://example.test/#tasks',runScripts:'outside-only'});
 const w=dom.window,d=w.document,calls=[];w.SbCabinet={registerView:(_,view)=>w.taskView=view};w.eval(fs.readFileSync(__dirname+'/tasks.js','utf8'));
 const entry={id:1,taskRef:'Deploy <script>bad</script>',threadId:'test-thread',executor:'Codex',scope:'CRM only',notBefore:'2026-10-08T11:00:00Z',durationMinutes:5};
 let state={resource:'synapse-production',revision:1,state:'unknown',fence:0,checkedAt:'',evidence:'',serverTime:'2026-10-08T11:00:00Z',holder:null,queue:[entry],history:[],nextCheckAt:'2026-10-08T11:05:00Z'},failClaim=false;
 const ctx={identity:{role:'owner'},currentView:'tasks',selectedProjectId:'alvi',byId:id=>d.getElementById(id),escapeHTML:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),scopeParams:()=>({companyCode:'alvi'}),hasPermission:()=>true,csrfOptions:(method,body)=>({method,body}),chooseProject:()=>{},navigate:()=>{},crmQuery:async(path,params,options)=>{calls.push({path,params,options});if(path==='/tasks/summary')return{};if(path==='/coordination/tasks')return{tasks:[],pagination:{total:0}};if(path==='/coordination/server-resource')return structuredClone(state);if(path.endsWith('/action')){const b=options.body;assert.equal(b.revision,state.revision);if(b.action==='confirm_idle')state={...state,revision:state.revision+1,state:'idle',evidence:b.evidence};if(b.action==='claim'){if(failClaim)throw Error('Связь потеряна, исход неизвестен');state={...state,revision:state.revision+1,state:'running',fence:1,queue:[],holder:{...entry,startedAt:state.serverTime,leaseUntil:'2026-10-08T11:05:00Z'}};return{resource:state,leaseToken:'test-opaque-lease'};}if(b.action==='release'){assert.equal(b.leaseToken,'test-opaque-lease');assert.equal(b.fence,1);state={...state,revision:state.revision+1,state:'idle',holder:null};}return{resource:state};}if(path.endsWith('/requests')){assert.ok(options.body.requestKey);return{};}throw Error(path);}};
 w.taskView.render(d.getElementById('tasks-content'),ctx);return{w,d,calls,fail:()=>failClaim=true,close:()=>w.close()};
}
test('resource UI separates unknown from free, escapes text and only releases the session lease with evidence',async()=>{const f=fixture();try{await settle();f.d.querySelector('[data-coord-server]').click();await settle();assert.match(f.d.body.textContent,/Требуется проверка/);assert.equal(f.d.querySelector('[data-resource-claim]'),null);assert.equal(f.d.querySelector('script'),null);const form=f.d.querySelector('[data-resource-idle]');form.elements.evidence.value='Verified idle';form.dispatchEvent(new f.w.Event('submit',{cancelable:true}));await settle();f.d.querySelector('[data-resource-claim]').click();await settle();assert.match(f.d.body.textContent,/Сейчас: Codex/);assert.ok(!f.d.body.textContent.includes('test-opaque-lease'));f.d.querySelector('[data-resource-release]').click();await settle();assert.match(f.d.body.textContent,/Укажите проверенный результат/);assert.equal(f.calls.filter(c=>c.options?.body?.action==='release').length,0);f.d.querySelector('[data-resource-release-note]').value='Finished, verified and no pending writes';f.d.querySelector('[data-resource-release]').click();await settle();assert.equal(f.calls.filter(c=>c.options?.body?.action==='release').length,1);assert.equal(f.d.querySelector('[data-resource-release]'),null);}finally{f.close();}});
test('unknown claim response stays disabled and directs readback, without blind retry',async()=>{const f=fixture();try{await settle();f.d.querySelector('[data-coord-server]').click();await settle();const form=f.d.querySelector('[data-resource-idle]');form.elements.evidence.value='Verified idle';form.dispatchEvent(new f.w.Event('submit',{cancelable:true}));await settle();f.fail();f.d.querySelector('[data-resource-claim]').click();await settle();assert.equal(f.d.querySelector('[data-resource-claim]').disabled,true);assert.match(f.d.body.textContent,/неизвестное действие не повторяйте/);assert.equal(f.calls.filter(c=>c.options?.body?.action==='claim').length,1);}finally{f.close();}});
